name: Auto-Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build

      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*
          name: "Onyx Client ${{ github.ref_name }} for Minecraft 1.21.5"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
