name: Auto-Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Clean build directory
        run: ./gradlew clean

      - name: Build the project
        run: ./gradlew build

      - name: Remove source jars
        run: rm -f build/libs/*-sources.jar

      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*
          name: "Onyx Client ${{ github.ref_name }} for Minecraft 1.21.5"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get built JAR path
        id: get-jar
        run: |
          JAR_FILE=$(find build/libs -maxdepth 1 -type f -name "*.jar" ! -name "*-sources.jar" | head -n 1)
          echo "jar=$JAR_FILE" >> "$GITHUB_OUTPUT"

      - name: Remove first character from version tag
        run: echo "VERSION_NUMBER=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: sIVsLoIb
          name: "Onyx Client ${{ github.ref_name }}"
          version: ${{ env.VERSION_NUMBER }}
          changelog: ""
          loaders: fabric
          game-versions: 1.21.5
          files: ${{ steps.get-jar.outputs.jar }}
          dependencies: '[{"project_id":"P7dR8mSH","dependency_type":"required"}]'